ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.netbug94.ApplicationKt.module ]
    }
}

# Your proprietary app settings map to environment variables
app {
    mensajero {
        phone = ${?MENSAJERO_PHONE}
        apiKey = ${?HERALDO_INTERNAL_TOKEN}
        url = ${?MENSAJERO_URL}
        template = ${?MENSAJERO_TEMPLATE}
    }
    timezone {
        gistUrl = ${?GIST_TIMEZONE_URL}
    }
    reminders {
        leadTimeMinutes = ${?ALERT_LEAD_TIME_MINUTES}
        allDayMensajeroTime = ${?ALL_DAY_MENSAJERO_TIME}
        summaryTaskTime = ${?SUMMARY_TASK_TIME}
        heartbeatTime = ${?HEARTBEAT_TIME}
    }
    dashboard {
        user = ${?DASHBOARD_USER}
        password = ${?DASHBOARD_PASSWORD}
    }
}